#!/bin/sh
# -*- sh-basic-offset: 2 -*-

##
# Copyright (c) 2005-2014 Apple Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

set -e
set -u

wd="$(cd "$(dirname "$0")/.." && pwd)";

. "${wd}/bin/_build.sh";

#
# It's entirely ridiculous that we have to *build* our C dependencies in order
# to simply download our Python dependencies, but in order to calculate
# dependencies, setuptools needs to basically run "setup.py egg_info", and
# some packages require the C dependencies in order to do this, and several
# even build stuff in this case.
#
# So the caclulation work here is enormous when it should be rather simple.
#
# Then, of course, we throw most of that work away, because we don't want build
# products here, just the source files.
#
# Oy.
#

init_build;
c_dependencies;

requirements="${wd}/requirements-apple.txt";
#extra_features="$("${python}" -c 'import setup; print ",".join(sorted(setup.extras_requirements.keys()))' | sed 's|Oracle,||')";
extra_features="OpenDirectory,Postgres";

ruler "Downloading Python requirements for .[${extra_features}]";
echo "";
pip_download \
  --allow-unverified cx-Oracle \
  --requirement="${requirements}" \
  ;
