#!/bin/sh
# -*- sh-basic-offset: 2 -*-

##
# Copyright (c) 2005-2014 Apple Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

set -e
set -u

wd="$(cd "$(dirname "$0")/.." && pwd)";

. "${wd}/bin/_build.sh";

init_build;

export PATH="/Applications/Server.app/Contents/ServerRoot/usr/bin:${PATH}";

requirements="${wd}/requirements-apple.txt";
extra_features="OpenDirectory,Postgres";


#
# Download virtualenv and friends.
#

mkdir -p "${wd}/.develop/tools";

for pkg in \
    pip-1.5.4 \
    virtualenv-1.11.4 \
    setuptools-3.4.4 \
; do
       name="${pkg%-*}";
    version="${pkg#*-}";
     first="$(echo "${name}" | sed 's|^\(.\).*$|\1|')";
       url="https://pypi.python.org/packages/source/${first}/${name}/${pkg}.tar.gz";

    ruler "Downloading ${pkg}";

    curl -L -o "${wd}/.develop/tools/${pkg}.tgz" "${url}";
done;


#
# Download dependencies
#

ruler "Downloading Python requirements for .[${extra_features}]";
echo "";
pip_download \
  --allow-unverified cx-Oracle \
  --requirement="${requirements}" \
  ;



#
# Remove .exe files from arvhives
#

for archive in $(find "${wd}/.develop" -type f -name '*.tgz'); do
  ruler "Cleaning up ${archive}";
  tmp="$(mktemp -d -t fooXXXX)";
  tar -C "${tmp}" --exclude '*.exe' -xzf "${archive}";
  tar -C "${tmp}" -czf "${archive}" .;
  rm -rf "${tmp}";
done;
