#!/bin/sh

##
# Copyright (c) 2005-2013 Apple Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

set -e
set -u

wd="$(cd "$(dirname "$0")/.." && pwd -P)";

docroot="${wd}/data/doc";

. "${wd}/support/build.sh";

do_setup="false";
  do_get="false";

dependencies;

##
# Generate documentation
##

mkdir -p "${docroot}";

set - -; shift; # Not sure how else to clear "$@"...

for package in twisted pycalendar; do
  package_dir="$(dirname "$(python -c "import ${package}; print ${package}.__file__")")";
  set - "$@" "--add-package=${package_dir}";
done;

for package in twext txdav twistedcaldav calendarserver; do
  set - "$@" "${package}";
done;

echo "Generating TwistedCalDAV documentation...";
pydoctor                                             \
  --project-name="CalendarServer"                    \
  --project-url="http://www.calendarserver.org/"     \
  --resolve-aliases                                  \
  --make-html --html-output="${docroot}/apidocs" \
  "$@";

#  --html-viewsource-base="http://trac.calendarserver.org/browser/CalendarServer/trunk" \
#  --html-use-splitlinks \
#  --html-use-sorttable \
#  --html-shorten-lists \
