#!/bin/sh

set -e
set -u

for revision; do
    revision="${revision#r}"; # Remove leading 'r'

    if ! test "${revision}" -gt 0 2>&1 >/dev/null; then
        echo "Invalid revision: ${revision}";
        exit 1;
    fi;

    previous=$((${revision} - 1));

    echo "Pulling up r${revision}...";
    svn merge "-r${previous}:${revision}" http://svn.macosforge.org/repository/calendarserver/CalendarServer/trunk;
done;
