#!/bin/sh

set -e
set -u

base="${1}";
if [ $# == 1 ]; then
  appbase="/Applications/Server.app/Contents/ServerRoot/Library/CalendarServer";
else
  appbase="${2}";
fi;

# Remove python binaries
rm -f "${base}/bin/python";
rm -f "${base}/bin/python2";
rm -f "${base}/bin/python2.7";

# Remove unused virtualenv files
rm -f "${base}/lib/python2.7/"*.py*;
rm -f "${base}/lib/python2.7/config";
rm -rf "${base}/lib/python2.7/distutils";
rm -f "${base}/lib/python2.7/encodings";
rm -f "${base}/lib/python2.7/lib-dynload";
rm -f "${base}/lib/python2.7/orig-prefix.txt";

# New python shim that sets up paths and runs the system python
cat - > "${base}/bin/python" <<EOF
#!/bin/sh

export PATH=${appbase}/bin:\${PATH};
export PYTHONPATH=${appbase}/lib/python2.7/site-packages;

exec /usr/bin/python "\${@}";
EOF

chmod a+x "${base}/bin/python";
ln -s "${appbase}/bin/python" "${base}/bin/python2";
ln -s "${appbase}/bin/python" "${base}/bin/python2.7";
