#!/bin/sh

##
# Copyright (c) 2015 Apple Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

set -e
set -u

base="${1}";
if [ $# == 1 ]; then
  appbase="/Applications/Server.app/Contents/ServerRoot/Library/CalendarServer";
else
  appbase="${2}";
fi;

# Remove python binaries
rm -f "${base}/bin/python";
rm -f "${base}/bin/python2";
rm -f "${base}/bin/python2.7";

# Remove unused virtualenv files
rm -f "${base}/.Python";
rm -f "${base}/include/python2.7";
rm -f "${base}/lib/python2.7/"*.py*;
rm -f "${base}/lib/python2.7/config";
rm -rf "${base}/lib/python2.7/distutils";
rm -f "${base}/lib/python2.7/encodings";
rm -f "${base}/lib/python2.7/lib-dynload";
rm -f "${base}/lib/python2.7/orig-prefix.txt";

# Create links
cd "${base}/bin"
ln -s "python-wrapper" "python";
ln -s "python-wrapper" "python2";
ln -s "python-wrapper" "python2.7";
