#!/usr/bin/env bash

##
# Copyright (c) 2005-2007 Apple Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

wd="$(cd "$(dirname "$0")" && pwd)";
cdt="${wd}/../CalDAVTester";

##
# Command line handling
##

verbose="";
serverinfo="${cdt}/scripts/server/serverinfo.xml";
documentroot="${wd}/data/Documents";

usage ()
{
  program="$(basename "$0")";
  echo "Usage: ${program} [-v] [-d docroot] [-s serverinfo]";
  echo "Options:";
  echo "        -h  Print this help and exit";
  echo "        -d  Set the document root";
  echo "        -s  Set the serverinfo.xml";
  echo "        -v  Verbose.";

  if [ "${1-}" == "-" ]; then return 0; fi;
  exit 64;
}

while getopts 'hvd:s:' option; do
  case "$option" in 
    '?') usage; ;;
    'h') usage -; exit 0; ;;
    'd') documentroot="${OPTARG}"; ;;
    's')   serverinfo="${OPTARG}"; ;;
    'v')      verbose="v"; ;;
  esac;
done;

shift $((${OPTIND} - 1));

if [ $# == 0 ]; then
  set - "--all";
fi;

##
# Do The Right Thing
##

. "${wd}/support/shell.sh"

if [ ! -e "${documentroot}/calendars/__uids__/user09" ]; then
  curl "http://localhost:8008/calendars/__uids__/user09/";
fi;

"${python}" twistedcaldav/test/data/makelargecalendars.py -o 9 -d "${documentroot}";

cd "${cdt}" && "${python}" testcaldav.py -s "${serverinfo}" "$@";

