#!/bin/sh

##
# Copyright (c) 2005-2006 Apple Computer, Inc. All rights reserved.
#
# This file contains Original Code and/or Modifications of Original Code
# as defined in and that are subject to the Apple Public Source License
# Version 2.0 (the 'License'). You may not use this file except in
# compliance with the License. Please obtain a copy of the License at
# http://www.opensource.apple.com/apsl/ and read it before using this
# file.
# 
# The Original Code and all software distributed under the License are
# distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
# EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
# INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
# Please see the License for the specific language governing rights and
# limitations under the License.
#
# DRI: Wilfredo Sanchez, wsanchez@apple.com
##

wd="$(cd "$(dirname "$0")" && pwd)";

##
# Command line handling
##

verbose="";
serverinfo="serverinfo.xml";
documentroot="${wd}/twistedcaldav/test/data";

usage ()
{
    program="$(basename "$0")";
    echo "Usage: ${program} [-v] [-d docroot] [-s serverinfo]";
    echo "Options:";
    echo "        -h  Print this help and exit";
    echo "        -d  Set the document root";
    echo "        -s  Set the serverinfo.xml";
    echo "        -v  Verbose.";

    if [ "${1-}" == "-" ]; then return 0; fi;
    exit 64;
}

while getopts 'hvd:s:' option; do
    case "$option" in 
        '?') usage; ;;
        'h') usage -; exit 0; ;;
        'd') documentroot=${OPTARG}; ;;
        's')   serverinfo=${OPTARG}; ;;
        'v')      verbose="v"; ;;
    esac;
done;

shift $((${OPTIND} - 1));

if [ $# != 0 ]; then usage "Unrecognized arguments:" "$@"; fi;

##
# Do The Right Thing
##

export PYTHONPATH=$("${wd}/run" -p);

cdt="${wd}/../CalDAVTester";

if [ -f "${cdt}" ]; then
  cd "${cdt}";
  svn update .;
else
  svn checkout http://macosxserver.apple.com:8000/svn/CalDAVTester/trunk "${cdt}"
fi;

cd "${documentroot}/calendars/users/user01/"
tar -zx${verbose}f "${cdt}/Resource/errors/calendar.1000.tgz"

cd "${cdt}";

python testcaldav.py -s "${serverinfo}" --all;
