#!/usr/bin/env bash

##
# Copyright (c) 2005-2013 Apple Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

wd="$(cd "$(dirname "$0")" && pwd)";
cdt="${wd}/../CalDAVTester";

##
# Command line handling
##

verbose="";
serverinfo="${cdt}/scripts/server/serverinfo.xml";
printres="";
subdir="";
random="--random";
seed="";

usage ()
{
  program="$(basename "$0")";
  echo "Usage: ${program} [-v] [-s serverinfo]";
  echo "Options:";
  echo "        -d  Set the script subdirectory";
  echo "        -h  Print this help and exit";
  echo "        -o  Execute tests in order";
  echo "        -r  Print request and response";
  echo "        -s  Set the serverinfo.xml";
  echo "        -t  Set the CalDAVTester directory";
  echo "        -x  Random seed to use.";
  echo "        -v  Verbose.";

  if [ "${1-}" == "-" ]; then return 0; fi;
  exit 64;
}

while getopts 'hvrot:s:d:' option; do
  case "$option" in 
    '?') usage; ;;
    'h') usage -; exit 0; ;;
    't') cdt="${OPTARG}"; serverinfo="${OPTARG}/scripts/server/serverinfo.xml"; ;;
    'd') subdir="--subdir=${OPTARG}"; ;;
    's') serverinfo="${OPTARG}"; ;;
    'r') printres="--always-print-request --always-print-response"; ;;
    'v') verbose="v"; ;;
    'o') random=""; ;;
    'x') seed="--random-seed ${OPTARG}"; ;;
  esac;
done;

shift $((${OPTIND} - 1));

if [ $# == 0 ]; then
  set - "--all";
fi;

##
# Do The Right Thing
##

source "${wd}/support/shell.sh";

cd "${cdt}" && "${python}" testcaldav.py ${random} ${seed} --print-details-onfail ${printres} -s "${serverinfo}" ${subdir} "$@";

