#!/bin/sh

##
# Copyright (c) 2005-2007 Apple Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# DRI: Wilfredo Sanchez, wsanchez@apple.com
##

usage ()
{
  program="$(basename "$0")";

  if [ "${1--}" != "-" ]; then echo "$@"; echo; fi;

  echo "Usage: ${program} [-hn]";
  echo "Options:";
  echo "        -h  Print this help and exit";
  echo "        -n  Do not use color";

  if [ "${1-}" == "-" ]; then return 0; fi;
  exit 64;
}


while getopts 'nh' option; do
  case "$option" in
    '?') usage; ;;
    'h') usage -; exit 0; ;;
    'n') trial_args="--reporter=bwverbose"; ;;
  esac;
done;
shift $((${OPTIND} - 1));

if [ $# != 0 ]; then usage "Unrecognized arguments:" "$@"; fi;


     wd="$(cd "$(dirname "$0")" && pwd -L)";
twisted="$(cd "${wd}/.." && pwd -L)/Twisted";

export PYTHONPATH="$("${wd}/run" -p)";

ulimit -S -n 2048;

if [ $# -gt 0 ]; then
    test_modules="$@";
else
    test_modules="twistedcaldav";
fi;

cd "${wd}" && "${twisted}/bin/trial" ${trial_args} ${test_modules};
