#!/bin/sh

##
# Copyright (c) 2005-2006 Apple Computer, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# DRI: Wilfredo Sanchez, wsanchez@apple.com
##

set -e
set -u

 wd="$(cd "$(dirname "$0")" && pwd -P)";
top="$(cd "${wd}/../.." && pwd -L)"

export PYTHONPATH="$("${wd}/../run" -p)";

##
# Download and set up dependancies
##

epydoc="${top}/epydoc-2.1";

if [ ! -d "${epydoc}" ]; then
   echo "Downloading Epydoc...";
   cd "${top}" && curl http://easynews.dl.sourceforge.net/sourceforge/epydoc/epydoc-2.1.tar.gz | tar xvzf -;
fi;

if [ ! -d "${epydoc}/build/lib" ]; then
   cd "${epydoc}" && python ./setup.py build
fi;

export PYTHONPATH="${PYTHONPATH}:${epydoc}/build/lib";

python_version="$(python -V 2>&1)";
python_version="${python_version#Python }";
python_version="${python_version%*.*}";

epydoc="${epydoc}/build/scripts-${python_version}/epydoc";

##
# Generate documentation
##

"${epydoc}" --check		\
    --ignore-param-mismatch	\
    "${wd}/../twistedcaldav";

rm -rf "${wd}/html";

"${epydoc}" -n "TwistedCalDAV"  \
    --ignore-param-mismatch	\
    --html -o "${wd}/html"	\
    --private			\
    "${wd}/../twistedcaldav";

open "${wd}/html/index.html";
